name: Pull Request Test
on: [pull_request]
jobs:
  build:
    name: Run make
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Set up kubebuilder
        run: "curl -L -O https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.1/kubebuilder_2.3.1_darwin_amd64.tar.gz; tar -zxvf kubebuilder_2.3.1_darwin_amd64.tar.gz; mv kubebuilder_2.3.1_darwin_amd64 kubebuilder; sudo mv kubebuilder/bin/* /usr/bin/;"
      - name: Make test
        run: make test
