name: Pull Request Test
on: [pull_request]
jobs:
  build:
    name: Run make
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Make test
        run: sudo make test
        env:
          GOPATH: "/github/home/go/"
